// Mocks generated by Mockito 5.4.6 from annotations
// in pet_community_app/test/mock_up/test_api_codes.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:my_api_client/src/dio_api_client/api_client.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i3.ApiClient {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response<dynamic>> get(
    String? requestUrl, {
    bool? needAuth = false,
    bool? external = false,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    Map<String, dynamic>? body,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [requestUrl],
          {
            #needAuth: needAuth,
            #external: external,
            #queryParameters: queryParameters,
            #options: options,
            #body: body,
            #cancelToken: cancelToken,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #get,
            [requestUrl],
            {
              #needAuth: needAuth,
              #external: external,
              #queryParameters: queryParameters,
              #options: options,
              #body: body,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> post(
    String? requestUrl, {
    bool? needAuth = false,
    bool? external = false,
    bool? useFormData = false,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    Map<String, dynamic>? body,
    Map<String, _i5.File>? files,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [requestUrl],
          {
            #needAuth: needAuth,
            #external: external,
            #useFormData: useFormData,
            #queryParameters: queryParameters,
            #options: options,
            #body: body,
            #files: files,
            #cancelToken: cancelToken,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #post,
            [requestUrl],
            {
              #needAuth: needAuth,
              #external: external,
              #useFormData: useFormData,
              #queryParameters: queryParameters,
              #options: options,
              #body: body,
              #files: files,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> put(
    String? requestUrl, {
    bool? needAuth = false,
    bool? external = false,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    Map<String, dynamic>? body,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [requestUrl],
          {
            #needAuth: needAuth,
            #external: external,
            #queryParameters: queryParameters,
            #options: options,
            #body: body,
            #cancelToken: cancelToken,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #put,
            [requestUrl],
            {
              #needAuth: needAuth,
              #external: external,
              #queryParameters: queryParameters,
              #options: options,
              #body: body,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> patch(
    String? requestUrl, {
    bool? needAuth = false,
    bool? external = false,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    Map<String, dynamic>? body,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [requestUrl],
          {
            #needAuth: needAuth,
            #external: external,
            #queryParameters: queryParameters,
            #options: options,
            #body: body,
            #cancelToken: cancelToken,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #patch,
            [requestUrl],
            {
              #needAuth: needAuth,
              #external: external,
              #queryParameters: queryParameters,
              #options: options,
              #body: body,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> delete(
    String? requestUrl, {
    bool? needAuth = false,
    bool? external = false,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    Map<String, dynamic>? body,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [requestUrl],
          {
            #needAuth: needAuth,
            #external: external,
            #queryParameters: queryParameters,
            #options: options,
            #body: body,
            #cancelToken: cancelToken,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #delete,
            [requestUrl],
            {
              #needAuth: needAuth,
              #external: external,
              #queryParameters: queryParameters,
              #options: options,
              #body: body,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);
}
